version: '3.8'
services:
  video:
    image: nginx:1.21.1
    container_name: nginx-video-server
    volumes:
      - ./video-server/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media/package:/usr/share/nginx/html:ro
    ports:
      - 8080:80
  
  player:
    image: nginx:1.21.1
    container_name: nginx-shaka-player
    volumes:
      - ./shaka-player:/usr/share/nginx/html:ro
    ports:
      - 8181:80